import {active,week,makeDraft,finish,uid,dateOnly,validate} from './model.js';
import {read,write,exportData} from './storage.js';
const root=document.querySelector('#app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'—';
let data,loadError=false,builder=null,historyProgram='',historyExercise='',toastTimer;
try{data=read()}catch(e){loadError=true;root.innerHTML=`<div class="card error"><h1>We couldn’t open your saved data</h1><p>Your saved data has been left untouched. Export a copy before trying to restore a backup.</p><button class="button" id="recover">Download saved data</button><p class="hint">${esc(e.message)}</p></div>`;document.querySelector('#recover').onclick=()=>{const raw=localStorage.getItem('workoutAppData');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([raw||''],{type:'application/json'}));a.download='setbook-recovery.json';a.click()};}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),3500)}
function save(){try{write(data);document.querySelectorAll('.save-label').forEach(el=>el.textContent='Saved on this device');return true}catch{toast('Couldn’t save. Storage may be full. Export a backup in Settings.');document.querySelectorAll('.save-label').forEach(el=>el.textContent='Not saved — export a backup');return false}}
function transaction(fn){const before=structuredClone(data);fn();if(save())return true;data=before;return false}
const name=id=>data.exercises.find(e=>e.id===id)?.name||'Exercise';
const exerciseOptions=chosen=>data.exercises.map(e=>`<option value="${esc(e.id)}" ${e.id===chosen?'selected':''}>${esc(e.name)}</option>`).join('');
const button=(text,action,extra='',type='')=>`<button class="button ${type}" data-action="${action}" ${extra}>${text}</button>`;
const heading=(eyebrow,title,sub='')=>`<div class="eyebrow">${eyebrow}</div><h1>${esc(title)}</h1>${sub?`<p class="muted">${sub}</p>`:''}`;
function home(){const p=active(data);if(!p)return `${heading('YOUR TRAINING, ONE SET AT A TIME','Make room for progress.')}<div class="welcome-layout"><div class="hero"><div class="eyebrow">YOUR NEXT TRAINING BLOCK</div><h2>A little structure.<br>A stronger routine.</h2><p class="hint">Your sessions. Your weights. Your pace.</p><div class="stats"><div><strong>01</strong><span>Build your program</span></div><div><strong>02</strong><span>Show up & log</span></div></div></div><div class="empty"><div class="symbol">▤</div><h2>${data.programs.length?'Ready for your next block?':'Let’s set up your training'}</h2><p class="muted">Choose your sessions and exercises. Setbook will remember the numbers, so you can focus on your workout.</p>${button('Create a program →','new-program')}</div></div>${data.programs.length?`<div class="section-title"><h2>Previous blocks</h2></div>${data.programs.map(p=>`<a class="card row" href="#history" data-history-program="${p.id}"><div><h3>${esc(p.name)}</h3><span class="hint">${data.workoutLogs.filter(l=>l.programId===p.id).length} workouts recorded</span></div><span>↗</span></a>`).join('')}`:''}`;
 const w=week(data,p),logs=data.workoutLogs.filter(l=>l.programId===p.id),done=logs.filter(l=>l.weekNumber===w).length;
 return `<div class="topline"><div>${heading('LET’S GET TO WORK','Your next set starts here.')}<p class="muted">${new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</p></div><span class="pill"><span class="status-dot"></span>On your device</span></div><div class="hero"><div class="row"><div><div class="eyebrow">ACTIVE TRAINING BLOCK</div><h2>${esc(p.name)}</h2><span class="hint">Week ${w} of ${p.weeks}</span></div><div class="big-number">${String(w).padStart(2,'0')}</div></div><div class="progress"><span style="width:${logs.length/(p.weeks*p.sessionsPerWeek)*100}%"></span></div><div class="stats"><div><strong>${logs.length}<span>sessions completed</span></strong></div><div><strong>${p.sessionsPerWeek}<span>sessions per week</span></strong></div></div></div>${data.draft?`<div class="notice row"><div><strong>Workout in progress</strong><br>${esc(p.sessionTemplates.find(s=>s.id===data.draft.sessionTemplateId)?.name)} · started ${fmt(data.draft.date)}</div>${button('Resume →','resume')}</div>`:''}<div class="section-title"><h2>This week’s sessions</h2><span class="hint">${done} / ${p.sessionsPerWeek} complete</span></div><div class="cards">${p.sessionTemplates.map((s,i)=>{const completed=logs.find(l=>l.weekNumber===w&&l.sessionTemplateId===s.id);return `<article class="card session ${completed?'done':''}"><div class="row"><div class="session-number">SESSION ${String(i+1).padStart(2,'0')}</div>${completed?'<span class="pill">✓ Complete</span>':''}</div><h3>${esc(s.name)}</h3><div class="hint">${s.exercises.length} exercises · ${s.exercises.reduce((n,e)=>n+e.defaultSets,0)} planned sets</div>${completed?`<span class="hint">Logged ${fmt(completed.date)}</span>`:button(data.draft?.sessionTemplateId===s.id?'Continue workout →':'Start workout →','start',`data-id="${s.id}"`,'secondary')}</article>`}).join('')}</div><p class="hint" style="margin-top:24px">Your week moves forward when every session is complete.</p>`;
}
function initBuilder(){builder={name:'',weeks:6,sessionsPerWeek:3,sessionTemplates:[1,2,3].map(i=>({id:uid(),name:`Session ${i}`,exercises:[]}))}}
function builderView(){const p=active(data);if(p&&!builder)return `${heading('YOUR TRAINING BLOCK',p.name)}<p class="muted">${p.weeks} weeks · ${p.sessionsPerWeek} sessions each week</p>${p.sessionTemplates.map(s=>`<div class="card"><h2>${esc(s.name)}</h2>${s.exercises.map(e=>`<div class="library-row"><div><strong>${esc(name(e.exerciseId))}</strong><div class="hint">${e.defaultSets} sets · ${e.repRangeMin}–${e.repRangeMax} reps · starting at ${e.startingWeight} kg</div>${e.notes?`<div class="hint">${esc(e.notes)}</div>`:''}</div></div>`).join('')}</div>`).join('')}<details><summary>Finish this block early</summary><p class="hint">Keep all recorded workouts in History and make room for a new block.</p>${button('Finish training block','archive','','danger')}</details>`;
 if(!builder)initBuilder();return `<div class="narrow">${heading('BUILD YOUR ROUTINE','A plan that fits you.','Set up once. Your numbers carry forward each session.')}<form id="builder-form"><div class="card"><div class="fields"><div class="full"><label for="program-name">Program name</label><input id="program-name" data-builder="name" value="${esc(builder.name)}" placeholder="e.g. Autumn strength block" maxlength="100" required></div><div><label for="program-weeks">Weeks</label><input id="program-weeks" type="number" min="1" max="52" data-builder="weeks" value="${builder.weeks}" required></div><div><label for="program-sessions">Sessions / week</label><select id="program-sessions" data-builder="sessionsPerWeek">${[1,2,3,4,5,6,7].map(n=>`<option ${n===builder.sessionsPerWeek?'selected':''}>${n}</option>`).join('')}</select></div></div></div>${builder.sessionTemplates.map((s,si)=>`<section class="card"><div class="eyebrow">SESSION ${String(si+1).padStart(2,'0')}</div><label for="session-${si}">Session name</label><input id="session-${si}" data-session="${si}" data-field="name" value="${esc(s.name)}" maxlength="100" required>${s.exercises.map((e,ei)=>`<div class="exercise-builder"><div class="row"><strong>${ei+1}. ${esc(name(e.exerciseId))}</strong><div class="stack"><button type="button" class="icon-button" data-action="move-exercise" data-si="${si}" data-ei="${ei}" ${ei===0?'disabled':''} aria-label="Move exercise up">↑</button><button type="button" class="icon-button" data-action="remove-exercise" data-si="${si}" data-ei="${ei}" aria-label="Remove exercise">×</button></div></div><div class="fields">${[['repRangeMin','Min reps',1,100],['repRangeMax','Max reps',1,100],['startingWeight','Weight · kg',0,2000],['defaultSets','Sets',1,20]].map(([f,l,min,max])=>`<div><label for="${si}-${ei}-${f}">${l}</label><input id="${si}-${ei}-${f}" type="number" min="${min}" max="${max}" step="${f==='startingWeight'?'any':'1'}" data-si="${si}" data-ei="${ei}" data-efield="${f}" value="${e[f]}" required></div>`).join('')}</div><label for="notes-${si}-${ei}">Setup notes</label><input id="notes-${si}-${ei}" data-si="${si}" data-ei="${ei}" data-efield="notes" value="${esc(e.notes)}" placeholder="e.g. Seat position 4" maxlength="1000"></div>`).join('')}<div class="fields two" style="margin-top:18px"><div><label for="pick-${si}">Add an exercise</label><select id="pick-${si}">${exerciseOptions()}</select></div><div style="align-self:end"><button type="button" class="button secondary" data-action="add-exercise" data-si="${si}">+ Add exercise</button></div></div><button type="button" class="text-button" data-action="custom-inline" data-si="${si}">+ Create a custom exercise</button></section>`).join('')}<div class="stack"><button class="button" type="submit">Save & start training →</button><button type="button" class="button secondary" data-action="cancel-builder">Cancel</button></div></form></div>`;
}
function workout(){const d=data.draft;if(!d)return home();const p=data.programs.find(p=>p.id===d.programId),s=p.sessionTemplates.find(s=>s.id===d.sessionTemplateId);return `<a class="back" href="#home">← Back to today</a><div class="topline"><div>${heading(`WEEK ${d.weekNumber} OF ${p.weeks} · ${fmt(d.date)}`,s.name)}</div><span class="pill">${d.exercises.length} exercises</span></div><p class="hint">Numbers are copied from your last session. Edit them or tap ✓ to confirm each set you performed.</p><div class="workout-list">${d.exercises.map((e,ei)=>{const template=s.exercises.find(x=>x.exerciseId===e.exerciseId);return `<section class="card exercise-card"><div class="eyebrow">EXERCISE ${String(ei+1).padStart(2,'0')}</div><h2>${esc(name(e.exerciseId))}</h2><div class="hint">${template.repRangeMin}–${template.repRangeMax} rep range${e.previousDate?` · Last: ${fmt(e.previousDate)} (week ${e.previousWeek})`:' · First session'}</div><div class="set-head"><span>Set</span><span style="text-align:center">Last time</span><span style="text-align:center">kg</span><span style="text-align:center">Reps</span><span>Done</span></div>${e.sets.map((t,ti)=>`<div class="set-row ${t.confirmed?'done':''}"><span class="set-no">${ti+1}</span><span class="previous">${t.previousWeight===null?'—':`${t.previousWeight} kg<br>× ${t.previousReps}`}</span><input aria-label="${esc(name(e.exerciseId))} set ${ti+1} weight in kg" type="number" inputmode="decimal" min="0" max="2000" step="any" value="${t.weight}" data-ei="${ei}" data-ti="${ti}" data-log="weight"><input aria-label="${esc(name(e.exerciseId))} set ${ti+1} reps" type="number" inputmode="numeric" min="0" max="1000" step="1" value="${t.reps}" placeholder="—" data-ei="${ei}" data-ti="${ti}" data-log="reps"><button class="set-check ${t.confirmed?'checked':''}" aria-label="Confirm ${esc(name(e.exerciseId))} set ${ti+1}" aria-pressed="${t.confirmed}" data-action="confirm-set" data-ei="${ei}" data-ti="${ti}">✓</button></div>`).join('')}<div class="row"><button class="text-button" data-action="add-set" data-ei="${ei}">+ Add set</button><button class="text-button" data-action="remove-set" data-ei="${ei}" ${e.sets.length<=1?'disabled':''}>− Remove last</button></div><label class="hint" for="log-notes-${ei}">Setup & session notes</label><textarea id="log-notes-${ei}" data-log-notes="${ei}" maxlength="2000" placeholder="Seat position, how it felt…">${esc(e.notes)}</textarea></section>`}).join('')}</div><div class="workout-footer"><span class="save-label">Saved on this device</span>${button('Session complete ✓','finish')}</div><details><summary>Discard this unfinished workout</summary><p class="hint">This removes only the current draft.</p>${button('Discard workout','discard','','danger')}</details>`;}
function history(){if(!data.programs.length)return `${heading('LOOK BACK','Your training history')}<div class="empty"><div class="symbol">↗</div><h2>Your first workout starts the story.</h2><p class="muted">Completed sets will appear here, organised by exercise and training block.</p><a class="button" href="#home">Back to today →</a></div>`;
 const p=data.programs.find(p=>p.id===historyProgram)||active(data)||data.programs.at(-1);historyProgram=p.id;const eids=[...new Set(p.sessionTemplates.flatMap(s=>s.exercises.map(e=>e.exerciseId)))];if(!eids.includes(historyExercise))historyExercise=eids[0];const logs=data.workoutLogs.filter(l=>l.programId===p.id);let rows=[];for(const l of logs){const e=l.exercises.find(e=>e.exerciseId===historyExercise);for(const t of e?.sets||[])rows.push({l,e,t})}return `${heading('THE WORK ADDS UP','Your training history','Every completed set, right where you left it.')}<div class="fields two"><div><label for="history-program">Training block</label><select id="history-program">${data.programs.map(p=>`<option value="${p.id}" ${p.id===historyProgram?'selected':''}>${esc(p.name)}${p.status==='completed'?' · completed':''}</option>`).join('')}</select></div><div><label for="history-exercise">Exercise</label><select id="history-exercise">${eids.map(id=>`<option value="${id}" ${id===historyExercise?'selected':''}>${esc(name(id))}</option>`).join('')}</select></div></div><div class="card"><div class="section-title" style="margin-top:0"><h2>${esc(name(historyExercise))}</h2><span class="pill">${rows.length} sets</span></div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Week</th><th>Session</th><th>Set</th><th>kg</th><th>Reps</th><th>Notes</th></tr></thead><tbody>${rows.sort((a,b)=>a.l.date.localeCompare(b.l.date)).map(({l,e,t})=>`<tr><td>${fmt(l.date)}</td><td>${l.weekNumber}</td><td>${esc(p.sessionTemplates.find(s=>s.id===l.sessionTemplateId)?.name)}</td><td>${t.setNumber}</td><td>${t.weight}</td><td>${t.reps}</td><td>${esc(e.notes)||'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">No completed sets for this exercise yet.</p>'}</div>`;}
function settings(){const custom=data.exercises.filter(e=>e.isCustom);return `<div class="narrow">${heading('MAKE IT YOURS','Settings')}<section class="card"><h2>Your data, on your device.</h2><p class="muted">Workouts save in this browser. Export a backup regularly, and before changing devices or clearing browser data.</p><div class="stack">${button('↓ Export backup','export')}<label class="button secondary" style="margin:0" for="import-file">↑ Restore backup</label><input id="import-file" type="file" accept=".json,application/json" hidden style="display:none"></div><p class="hint" style="margin-top:16px">Restoring replaces all current data, including an unfinished workout. You’ll be asked before anything changes.</p></section><section class="card"><h2>Exercise library</h2><p class="hint">${data.exercises.length} exercises available. Exercises used in a program are kept to protect your history.</p><form id="custom-form" class="row"><input aria-label="Custom exercise name" name="name" placeholder="New exercise name" maxlength="100" required><button class="button">Add</button></form>${custom.map(e=>`<div class="library-row"><span>${esc(e.name)}</span><button class="text-button" data-action="delete-custom" data-id="${e.id}">Remove</button></div>`).join('')}<details><summary>View included exercises</summary>${data.exercises.filter(e=>!e.isCustom).map(e=>`<div class="library-row">${esc(e.name)}</div>`).join('')}</details></section><section class="card"><h2>Take Setbook to the gym</h2><p class="hint">On your iPhone, open the published link in Safari. Tap Share, then Add to Home Screen. Open it once while connected and wait for “Ready offline” before your first offline workout.</p><p class="hint" id="offline-status">${offlineText}</p><div class="library-row"><span>Weight unit</span><strong>kg</strong></div><div class="library-row"><span>Week advances</span><strong>After all sessions</strong></div><div class="library-row"><span>Version</span><strong>1.0</strong></div></section></div>`;}
let offlineText='Offline setup pending';
function render(){if(loadError)return;const page=location.hash.slice(1)||'home';root.innerHTML=page==='program'?builderView():page==='workout'?workout():page==='history'?history():page==='settings'?settings():home();document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===(page==='workout'?'home':page)));}
function navigate(page){if(location.hash===`#${page}`)render();else location.hash=page;}
function addExercise(si,id){const s=builder.sessionTemplates[si];if(s.exercises.some(e=>e.exerciseId===id)){toast('That exercise is already in this session.');return}s.exercises.push({exerciseId:id,order:s.exercises.length,repRangeMin:8,repRangeMax:12,startingWeight:0,defaultSets:3,notes:''});render()}
function customExercise(n){n=n?.trim();if(!n)return null;const match=data.exercises.find(e=>e.name.toLowerCase()===n.toLowerCase());if(match)return match.id;const e={id:uid(),name:n.slice(0,100),isCustom:true};return transaction(()=>data.exercises.push(e))?e.id:null;}
root.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(event.target.closest('[data-history-program]'))historyProgram=event.target.closest('[data-history-program]').dataset.historyProgram;if(!b||loadError)return;const a=b.dataset.action,ei=Number(b.dataset.ei),ti=Number(b.dataset.ti),si=Number(b.dataset.si);
 if(a==='new-program'){initBuilder();navigate('program')}
 if(a==='cancel-builder'){builder=null;navigate('home')}
 if(a==='resume')navigate('workout');
 if(a==='add-exercise')addExercise(si,document.querySelector(`#pick-${si}`).value);
 if(a==='custom-inline'){const id=customExercise(prompt('Name your custom exercise'));if(id)addExercise(si,id)}
 if(a==='remove-exercise'){builder.sessionTemplates[si].exercises.splice(ei,1);render()}
 if(a==='move-exercise'){const e=builder.sessionTemplates[si].exercises;[e[ei-1],e[ei]]=[e[ei],e[ei-1]];render()}
 if(a==='start'){const p=active(data),s=p?.sessionTemplates.find(s=>s.id===b.dataset.id);if(!s)return;if(data.draft?.sessionTemplateId===s.id){navigate('workout');return}if(transaction(()=>{if(data.draft){if(!finish(data))data.draft=null;}data.draft=makeDraft(data,p,s)}))navigate('workout')}
 if(a==='confirm-set'){const t=data.draft.exercises[ei].sets[ti];if(t.weight===''||t.reps===''){toast('Enter weight and reps first.');return}if(transaction(()=>t.confirmed=!t.confirmed))render()}
 if(a==='add-set'){const e=data.draft.exercises[ei];if(e.sets.length>=50)return;if(transaction(()=>e.sets.push({setNumber:e.sets.length+1,weight:e.sets.at(-1)?.weight??0,reps:'',confirmed:false,previousWeight:null,previousReps:null})))render()}
 if(a==='remove-set'){const e=data.draft.exercises[ei];if(e.sets.at(-1).confirmed&&!confirm('Remove the last confirmed set?'))return;if(transaction(()=>e.sets.pop()))render()}
 if(a==='finish'){const invalid=root.querySelector('input:invalid');if(invalid){invalid.reportValidity();return}if(!data.draft.exercises.some(e=>e.sets.some(t=>t.confirmed))){toast('Confirm at least one performed set with ✓ first.');return}if(transaction(()=>finish(data))){navigate('home');toast('Session complete. Nice work.')}}
 if(a==='discard'&&confirm('Discard this unfinished workout? Your completed history will stay.')){if(transaction(()=>data.draft=null))navigate('home')}
 if(a==='archive'){if(data.draft){toast('Complete or discard your current workout first.');return}if(confirm('Finish this training block? Your workout history will be kept.')){if(transaction(()=>active(data).status='completed'))navigate('home')}}
 if(a==='export')exportData(data);
 if(a==='delete-custom'){if(data.programs.some(p=>p.sessionTemplates.some(s=>s.exercises.some(e=>e.exerciseId===b.dataset.id)))||builder?.sessionTemplates.some(s=>s.exercises.some(e=>e.exerciseId===b.dataset.id))){toast('This exercise is used in a program and needs to stay.');return}if(transaction(()=>data.exercises=data.exercises.filter(e=>e.id!==b.dataset.id)))render()}
});
root.addEventListener('input',event=>{const el=event.target,d=el.dataset;if(d.builder&&d.builder!=='sessionsPerWeek')builder[d.builder]=d.builder==='name'?el.value:Number(el.value);if(d.session!==undefined)builder.sessionTemplates[Number(d.session)][d.field]=el.value;if(d.efield)builder.sessionTemplates[Number(d.si)].exercises[Number(d.ei)][d.efield]=d.efield==='notes'?el.value:Number(el.value);if(d.log){const t=data.draft.exercises[Number(d.ei)].sets[Number(d.ti)];if(!el.validity.valid&&el.value!==''){document.querySelector('.save-label').textContent='Check this number — not saved';return}t[d.log]=el.value===''?'':Number(el.value);t.confirmed=t.weight!==''&&t.reps!=='';const row=el.closest('.set-row');row.classList.toggle('done',t.confirmed);row.querySelector('button').classList.toggle('checked',t.confirmed);row.querySelector('button').setAttribute('aria-pressed',String(t.confirmed));save()}if(d.logNotes!==undefined){data.draft.exercises[Number(d.logNotes)].notes=el.value;save()}});
root.addEventListener('change',async event=>{const el=event.target;if(el.dataset.builder==='sessionsPerWeek'){const n=Number(el.value);if(n<builder.sessionTemplates.length&&builder.sessionTemplates.slice(n).some(s=>s.exercises.length)&&!confirm('Remove the extra sessions from this draft program?')){el.value=builder.sessionsPerWeek;return}builder.sessionsPerWeek=n;while(builder.sessionTemplates.length<n)builder.sessionTemplates.push({id:uid(),name:`Session ${builder.sessionTemplates.length+1}`,exercises:[]});builder.sessionTemplates.length=n;render()}if(el.id==='history-program'){historyProgram=el.value;render()}if(el.id==='history-exercise'){historyExercise=el.value;render()}if(el.id==='import-file'){const f=el.files[0];if(!f)return;try{if(f.size>10*1024*1024)throw new Error('Please use a backup smaller than 10 MB.');const imported=validate(JSON.parse(await f.text()));if(confirm(`Restore ${imported.programs.length} program(s) and ${imported.workoutLogs.length} workout(s)? This replaces all current data. Export a backup first if needed.`)){const old=data;data=imported;if(!save())data=old;else{builder=null;render();toast('Backup restored.')}}}catch(e){toast(e.message)}el.value='';}});
root.addEventListener('submit',event=>{event.preventDefault();if(event.target.id==='custom-form'){if(customExercise(new FormData(event.target).get('name')))render()}if(event.target.id==='builder-form'){if(builder.sessionTemplates.some(s=>!s.exercises.length)){toast('Add at least one exercise to each session.');return}if(builder.sessionTemplates.some(s=>s.exercises.some(e=>e.repRangeMin>e.repRangeMax))){toast('Minimum reps cannot exceed maximum reps.');return}if(!builder.name.trim()||builder.sessionTemplates.some(s=>!s.name.trim())){toast('Give the program and every session a name.');return}const p={...structuredClone(builder),id:uid(),status:'active',startDate:dateOnly()};p.sessionTemplates.forEach(s=>s.exercises.forEach((e,i)=>e.order=i));if(transaction(()=>data.programs.push(p))){builder=null;navigate('home');toast('Your training block is ready.')}}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});
function connection(){document.querySelector('#connection').textContent=navigator.onLine?'Personal workout log':'Offline · on your device'}window.addEventListener('online',connection);window.addEventListener('offline',connection);connection();render();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{offlineText='✓ Ready offline';const el=document.querySelector('#offline-status');if(el)el.textContent=offlineText;}).catch(()=>{offlineText='Offline setup failed. Reopen while connected to try again.';const el=document.querySelector('#offline-status');if(el)el.textContent=offlineText;});}
