import {Cloud} from './cloud.js';
import {exportData} from './storage.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,extra='')=>`<button type="button" class="button secondary" data-cloud="${action}" ${extra}>${label}</button>`;
export function setupCloud({root,getData,onRestore,render,toast}){
 let versions=[];
 const cloud=new Cloud({getData,onRestore,onStatus:update});
 function view(){let data;try{data=getData();}catch(e){return '<section class="card"><h2>Cloud backup</h2><p>'+esc(e.message)+'</p></section>';}const session=cloud.session,remote=cloud.remote;return `<section class="card"><h2>Cloud backup</h2><p data-cloud-status role="status">${esc(cloud.status)}</p>${session?`<p class="hint">${esc(session.user.email)}</p><div class="stack">${button('Sync now','sync')}${button('Sign out','out')}</div>${cloud.choice?`<div class="notice"><p><strong>This device:</strong> ${data.programs.length} programs · ${data.workoutLogs.length} workouts${data.draft?' · unfinished session':''}</p><p><strong>Online:</strong> ${remote?`${remote.payload.programs.length} programs · ${remote.payload.workoutLogs.length} workouts · saved ${esc(new Date(remote.updated_at).toLocaleString())}`:'No backup yet'}</p><p class="hint">Choose the copy to keep using. A local recovery copy is saved first; earlier online versions remain available.</p><div class="stack">${button('Use this device','device')}${remote?button('Use online copy','download'):''}</div></div>`:''}<details><summary>Previous cloud versions</summary><p class="hint">Restore an earlier save if something went wrong. Your current copy is kept for recovery.</p>${button('Load versions','versions')}${versions.map(v=>`<div class="library-row"><span>${esc(new Date(v.created_at).toLocaleString())} · v${v.revision}</span>${button('Restore','restore',`data-revision="${v.revision}"`)}</div>`).join('')}</details>`:`<form id="cloud-login"><label for="cloud-email">Email</label><input id="cloud-email" name="email" type="email" autocomplete="email" required placeholder="Your email address"><button class="button" type="submit">Email me a sign-in link</button><p class="hint">Open the link on this device. Only your approved account can access workout backups.</p></form><details><summary>Sign in inside the Home Screen app</summary><p class="hint">In your email, press and hold the sign-in button and copy its link. Paste it here to stay in this app with your existing workouts.</p><form id="cloud-link"><label for="email-link">Email sign-in link</label><input id="email-link" name="link" type="url" autocomplete="off" required><button class="button" type="submit">Sign in here</button></form></details>`}<p class="hint">Workouts save on this device first. Once connected, changes upload automatically when online. Keep occasional exported backups too.</p><details><summary>Local recovery copies</summary><p class="hint">Download a copy saved before switching or restoring data, then use Restore backup below.</p>${Object.keys(localStorage).filter(k=>k.startsWith('setbook-recovery-')).sort().reverse().map(k=>button(esc(new Date(Number(k.split('-')[2])).toLocaleString()),'recovery',`data-key="${esc(k)}"`)).join('')||'<p class="hint">No recovery copies yet.</p>'}</details></section>`;}
 function update(){const panel=document.querySelector('#cloud-panel');if(panel){try{if(document.querySelector('#cloud-login'))document.querySelector('[data-cloud-status]').textContent=cloud.status;else panel.innerHTML=view();}catch{const el=document.querySelector('[data-cloud-status]');if(el)el.textContent=cloud.status;}}const status=document.querySelector('#connection');if(status&&cloud.session)status.textContent=navigator.onLine?cloud.status:'Offline · saved on this device';}
 root.addEventListener('click',async event=>{const b=event.target.closest('[data-cloud]');if(!b)return;const a=b.dataset.cloud;try{
  if(a==='sync')await cloud.sync();
  if(a==='out'){await cloud.signOut();versions=[];}
  if(a==='device'&&confirm('Use this device’s data for your online copy? Existing online versions will be kept.'))await cloud.choose('device');
  if(a==='download'&&confirm('Replace this device’s workouts with the online copy? A local recovery copy will be saved first.'))await cloud.choose('cloud');
  if(a==='versions')versions=await cloud.versions();
  if(a==='restore'&&confirm('Restore this earlier version on this device and online? Your current local data will be kept as a recovery copy.'))await cloud.restoreVersion(Number(b.dataset.revision));
  if(a==='recovery')exportData(JSON.parse(localStorage.getItem(b.dataset.key)));
 }catch(e){cloud.say(e.message);toast(e.message);}if(location.hash==='#settings')render();});
 root.addEventListener('submit',async event=>{if(!['cloud-login','cloud-link'].includes(event.target.id))return;event.preventDefault();const b=event.target.querySelector('button');b.disabled=true;try{if(event.target.id==='cloud-link'){const link=new FormData(event.target).get('link');event.target.reset();await cloud.useEmailLink(link);render();await cloud.sync();}else await cloud.sendLink(new FormData(event.target).get('email'));}catch(e){cloud.say(e.message);}finally{b.disabled=false;update();}});
 async function start(){const hash=location.hash;
  if(hash.includes('access_token=')||hash.includes('error_description=')){window.history.replaceState(null,'',location.pathname+location.search+'#settings');try{if(hash.includes('access_token='))await cloud.acceptLink(hash);else throw new Error('Sign-in link expired or failed. Request another link.');}catch(e){cloud.say(e.message);}render();}
  await cloud.sync();update();
 }
 window.addEventListener('online',()=>cloud.sync());window.addEventListener('focus',()=>cloud.sync());
 window.addEventListener('storage',event=>{if(event.key==='workoutAppData'){try{getData();}catch(e){cloud.say(e.message);toast(e.message);}}});
 setInterval(()=>{if(navigator.onLine)cloud.sync();},60000);
 return {view,schedule:()=>cloud.schedule(),start};
}
