export const uid=()=>globalThis.crypto.randomUUID();
export const dateOnly=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const starterNames=['Barbell bench press','Incline dumbbell press','Dumbbell shoulder press','Lateral raise','Cable fly','Triceps pushdown','Lat pulldown','Seated cable row','Barbell row','Dumbbell curl','Hammer curl','Back squat','Leg press','Romanian deadlift','Leg extension','Seated leg curl','Standing calf raise','Hip thrust','Pull-up','Push-up'];
export const fresh=()=>({schemaVersion:1,exercises:starterNames.map(name=>({id:uid(),name,isCustom:false})),programs:[],workoutLogs:[],draft:null});
export const active=d=>d.programs.find(p=>p.status==='active');
export function week(d,p){for(let w=1;w<=p.weeks;w++){if(!p.sessionTemplates.every(s=>d.workoutLogs.some(l=>l.programId===p.id&&l.sessionTemplateId===s.id&&l.weekNumber===w)))return w;}return p.weeks+1;}
export function previous(d,pid,sid,eid){return [...d.workoutLogs].reverse().find(l=>l.programId===pid&&l.sessionTemplateId===sid&&l.exercises.some(e=>e.exerciseId===eid&&e.sets.length));}
export function makeDraft(d,p,s){return {id:uid(),programId:p.id,sessionTemplateId:s.id,weekNumber:week(d,p),date:dateOnly(),startedAt:new Date().toISOString(),exercises:s.exercises.map(e=>{const log=previous(d,p.id,s.id,e.exerciseId),last=log?.exercises.find(x=>x.exerciseId===e.exerciseId);return {exerciseId:e.exerciseId,notes:last?.notes??e.notes,previousDate:log?.date??null,previousWeek:log?.weekNumber??null,sets:Array.from({length:last?.sets.length||e.defaultSets},(_,i)=>({setNumber:i+1,weight:last?.sets[i]?.weight??e.startingWeight,reps:last?.sets[i]?.reps??'',confirmed:false,previousWeight:last?.sets[i]?.weight??null,previousReps:last?.sets[i]?.reps??null}))};})};}
export function finish(d){if(!d.draft)return false;const log=structuredClone(d.draft);log.exercises=log.exercises.map(e=>({...e,sets:e.sets.filter(s=>s.confirmed&&s.reps!==''&&s.weight!=='').map((s,i)=>({setNumber:i+1,weight:Number(s.weight),reps:Number(s.reps)}))}));if(!log.exercises.some(e=>e.sets.length))return false;log.completedAt=new Date().toISOString();d.workoutLogs.push(log);d.draft=null;const p=active(d);if(p&&week(d,p)>p.weeks)p.status='completed';return true;}
export function validate(d){
 const fail=()=>{throw new Error('This is not a valid Setbook backup. Your current data has not changed.')};
 const str=x=>typeof x==='string'&&x.length<=20000;const num=(x,min=0,max=100000)=>typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max;const integer=(x,min,max)=>num(x,min,max)&&Number.isInteger(x);
 if(!d||d.schemaVersion!==1||!Array.isArray(d.exercises)||!Array.isArray(d.programs)||!Array.isArray(d.workoutLogs))fail();
 const ids=new Set();const id=x=>{if(!str(x)||!x||ids.has(x))fail();ids.add(x)};
 d.exercises.forEach(e=>{id(e.id);if(!str(e.name)||typeof e.isCustom!=='boolean')fail()});const eids=new Set(d.exercises.map(e=>e.id));
 d.programs.forEach(p=>{id(p.id);if(!str(p.name)||!['active','completed'].includes(p.status)||!integer(p.weeks,1,52)||!integer(p.sessionsPerWeek,1,7)||!Array.isArray(p.sessionTemplates)||p.sessionTemplates.length!==p.sessionsPerWeek)fail();p.sessionTemplates.forEach(s=>{id(s.id);if(!str(s.name)||!Array.isArray(s.exercises)||!s.exercises.length)fail();s.exercises.forEach(e=>{if(!eids.has(e.exerciseId)||!integer(e.repRangeMin,1,100)||!integer(e.repRangeMax,e.repRangeMin,100)||!num(e.startingWeight,0,2000)||!integer(e.defaultSets,1,20)||!str(e.notes))fail()});if(new Set(s.exercises.map(e=>e.exerciseId)).size!==s.exercises.length)fail()})});
 if(d.programs.filter(p=>p.status==='active').length>1)fail();
 const checkLog=(l,draft=false)=>{id(l.id);const p=d.programs.find(p=>p.id===l.programId),s=p?.sessionTemplates.find(s=>s.id===l.sessionTemplateId);if(!s||!integer(l.weekNumber,1,p.weeks)||!str(l.date)||!/^\d{4}-\d{2}-\d{2}$/.test(l.date)||!Array.isArray(l.exercises)||l.exercises.length!==s.exercises.length)fail();l.exercises.forEach((e,i)=>{if(e.exerciseId!==s.exercises[i].exerciseId||!str(e.notes)||!Array.isArray(e.sets)||e.sets.length>50)fail();e.sets.forEach(t=>{if(!integer(t.setNumber,1,50)||!(num(t.weight,0,2000)||(draft&&t.weight===''))||!(integer(t.reps,0,1000)||(draft&&t.reps===''))||(draft&&typeof t.confirmed!=='boolean'))fail()})});if(draft&&p.status!=='active')fail();};
 d.workoutLogs.forEach(l=>checkLog(l));if(d.draft){checkLog(d.draft,true);d.draft.exercises.forEach(e=>{if(!(e.previousDate===null||(str(e.previousDate)&&/^\d{4}-\d{2}-\d{2}$/.test(e.previousDate)))||!(e.previousWeek===null||integer(e.previousWeek,1,52)))fail();e.sets.forEach(s=>{if(!(s.previousWeight===null||num(s.previousWeight,0,2000))||!(s.previousReps===null||integer(s.previousReps,0,1000)))fail()})});}return d;
}
