const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Labels always accompany colour; all swatches use the same dark foreground.
export const muscleColours={Chest:'#f1b7ba',Back:'#adcce8',Shoulders:'#d0b9e6',Traps:'#b9c3d4',Biceps:'#f2c398',Triceps:'#edda8e',Forearms:'#d0d99b',Quads:'#b5d7ad',Hamstrings:'#9ed5c9',Glutes:'#e4b3d4',Calves:'#a5dce5',Abs:'#d8bc9f',Uncategorised:'#dddddd'};
export function previewTable(data,program,mode='groups'){
 const sessions=program.sessionTemplates,rows=Math.max(0,...sessions.map(s=>s.exercises.length)),library=new Map(data.exercises.map(e=>[e.id,e]));
 if(!rows)return '<p class="preview-empty">Add exercises to your sessions to see the layout here.</p>';
 return `<div class="program-preview-scroll" tabindex="0" role="region" aria-label="Program layout, scroll horizontally to see all sessions"><table class="program-preview-table ${mode==='exercises'?'show-exercises':''}" style="--session-count:${sessions.length}"><caption class="sr-only">${esc(program.name||'Untitled program')}: ${mode==='exercises'?'exercises':'muscle groups'} in planned exercise order</caption><thead><tr><th scope="col" class="preview-order"><span aria-hidden="true">#</span><span class="sr-only">Exercise order</span></th>${sessions.map((s,i)=>`<th scope="col"><span class="preview-session-number">Session ${i+1}</span><span>${esc(s.name||`Session ${i+1}`)}</span></th>`).join('')}</tr></thead><tbody>${Array.from({length:rows},(_,i)=>`<tr><th scope="row" class="preview-order">${i+1}</th>${sessions.map(s=>{const planned=s.exercises[i];if(!planned)return '<td class="preview-gap"><span aria-hidden="true">—</span><span class="sr-only">No exercise in this position</span></td>';const exercise=library.get(planned.exerciseId),group=Object.hasOwn(muscleColours,exercise?.muscleGroup)?exercise.muscleGroup:'Uncategorised';return `<td style="background:${muscleColours[group]}">${mode==='exercises'?`<span class="preview-exercise-name">${esc(exercise?.name||'Unknown exercise')}</span><span class="preview-muscle-label">${esc(group)}</span>`:`<span>${esc(group)}</span>`}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`;
}
export function programPreview(data,program,mode='groups'){
 return `<a class="back" href="#program">← Back to program</a>${program?`<div class="preview-heading"><div><h1>Program preview</h1><p class="preview-program-name">${esc(program.name||'Untitled program')}</p></div><div class="preview-controls" role="group" aria-label="Preview content"><button type="button" data-action="preview-mode" data-mode="groups" aria-pressed="${mode==='groups'}">Muscle groups</button><button type="button" data-action="preview-mode" data-mode="exercises" aria-pressed="${mode==='exercises'}">Exercises</button></div></div><p class="hint preview-help">Read down each session in exercise order. Swipe across or turn your phone sideways for more space.</p><div id="program-preview-grid">${previewTable(data,program,mode)}</div>`:'<h1>Program preview</h1><p>This program is no longer available.</p>'}`;
}

