import {week} from './model.js';
import {escape as esc} from './views.js';
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'});
export function activeToday(data,p){
 const w=week(data,p),logs=data.workoutLogs.filter(l=>l.programId===p.id),done=logs.filter(l=>l.weekNumber===w).length,draft=data.draft;
 const draftSession=draft?data.programs.find(x=>x.id===draft.programId)?.sessionTemplates.find(x=>x.id===draft.sessionTemplateId):null;
 const confirmed=draft?.exercises.reduce((n,e)=>n+e.sets.filter(t=>t.confirmed&&Number(t.reps)>0&&t.weight!=='').length,0)||0;
 return `<div class="today-heading"><h1>Today</h1><p class="hint">${new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</p></div>${draft?`<section class="resume-card" aria-labelledby="resume-title"><div class="resume-status"><span class="status-dot"></span>Workout in progress</div><h2 id="resume-title">${esc(draftSession?.name||'Your workout')}</h2><p>Week ${draft.weekNumber} · ${confirmed} ${confirmed===1?'set':'sets'} completed · started ${fmt(draft.date)}</p><button class="button resume-button" data-action="resume">Resume workout →</button></section>`:''}<section class="active-block-summary" aria-label="Active training block"><div><span class="active-block-label">Active training block</span><h2>${esc(p.name)}</h2><p class="hint">Week ${Math.min(w,p.weeks)} of ${p.weeks} · ${logs.length} / ${p.weeks*p.sessionsPerWeek} sessions complete</p></div><a href="#program" class="text-button" aria-label="View active program">View →</a></section><div class="section-title"><h2>This week’s sessions</h2><span class="hint">${done} / ${p.sessionsPerWeek} complete</span></div><div class="cards">${p.sessionTemplates.map((s,i)=>{const completed=logs.find(l=>l.weekNumber===w&&l.sessionTemplateId===s.id);return `<article class="card session ${completed?'done':''}"><div class="row"><div class="session-number">SESSION ${String(i+1).padStart(2,'0')}</div>${completed?'<span class="pill">✓ Complete</span>':''}</div><h3>${esc(s.name)}</h3><div class="hint">${s.exercises.length} exercises · ${s.exercises.reduce((n,e)=>n+e.defaultSets,0)} planned sets</div>${completed?`<span class="hint">Logged ${fmt(completed.date)}</span>`:`<button class="button secondary" data-action="start" data-id="${esc(s.id)}">${draft?.sessionTemplateId===s.id?'Continue workout →':'Start workout →'}</button>`}</article>`}).join('')}</div><p class="hint" style="margin-top:24px">Your week moves forward when every session is complete.</p>`;
}
